### ISSUE TITLE
Issues with Tiddlywiki 5.2 upgrade

### ISSUE THREAD

**Issue by h6y3** [sobjornstad/TiddlyRemember#52]
I foolishly updated to the latest Tiddlywiki 5.2 and discovered that upon upgrade it appears that things have broken on Tiddlyremember.  I'm using Nodejs on the server side and version 2.1.44 on the client-side (M1 Mac).  I had no problems until I upgraded, but as far as I can tell nothing else but Tiddlyremember broke; which is terrible since this is the plugin I use daily.

Here's the error I get on the client-side:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-10-26 12:10:20
Add-ons possibly involved: ⁨TiddlyRemember⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/hyuan/Library/Application Support/Anki2/addons21/60456529/twimport.py", line 61, in _invoke_tw_command
    proc = subprocess.run(cmd, cwd=wiki_path, stdout=subprocess.PIPE,
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/tiddlyremember', '--load', '/var/folders/36/rgts6_wd0559_p1z444ngh600000gn/T/tmp_lkbeydl/wiki.html', '--savewikifolder', '/var/folders/36/rgts6_wd0559_p1z444ngh600000gn/T/tmp_lkbeydl/wikifolder']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hyuan/Library/Application Support/Anki2/addons21/60456529/__init__.py", line 187, in join_thread
    if self.handle_thread_exception():
  File "/Users/hyuan/Library/Application Support/Anki2/addons21/60456529/__init__.py", line 175, in handle_thread_exception
    raise exc
  File "/Users/hyuan/Library/Application Support/Anki2/addons21/60456529/__init__.py", line 62, in run
    self.notes = twimport.find_notes(
  File "/Users/hyuan/Library/Application Support/Anki2/addons21/60456529/twimport.py", line 195, in find_notes
    _folderify_wiki(tw_binary, downloaded_file, wiki_folder)
  File "/Users/hyuan/Library/Application Support/Anki2/addons21/60456529/twimport.py", line 52, in _folderify_wiki
    _invoke_tw_command(cmd, None, "folderify wiki")
  File "/Users/hyuan/Library/Application Support/Anki2/addons21/60456529/twimport.py", line 72, in _invoke_tw_command
    raise RenderingError(
60456529.oops.RenderingError: Failed to folderify wiki: return code 1.
$ /usr/local/bin/tiddlyremember --load /var/folders/36/rgts6_wd0559_p1z444ngh600000gn/T/tmp_lkbeydl/wiki.html --savewikifolder /var/folders/36/rgts6_wd0559_p1z444ngh600000gn/T/tmp_lkbeydl/wikifolder

[1;31mError: No tiddlers found in file "/var/folders/36/rgts6_wd0559_p1z444ngh600000gn/T/tmp_lkbeydl/wiki.html"[0m
```

**Comment by crazko** [comment]
Just to add info for those with the same error - when updating the TiddlyWiki version, do not forget to update also the one installed on Node.js as specified in [Step 2 of installation steps](https://sobjornstad.github.io/TiddlyRemember/#Installing%20TiddlyRemember).

---

Unfortunately, I'm now stucked with #40, and have not yet been able to find a solution.

**Comment by sobjornstad** [comment]
@crazko: Have you tried rebooting yet? If this is a file locking issue as I suspect, that may resolve it – surprised I forgot to suggest that in #40.
