### ISSUE TITLE
Support encrypted/passworded wikis

### ISSUE THREAD

**Issue by sobjornstad** [sobjornstad/TiddlyRemember#7]
Will have to think about where/how/if this information should be stored. Should be relatively straightforward though -- as Si [points out](https://groups.google.com/d/msg/tiddlywiki/UD6VyV_r-94/m27nxKs2AQAJ) there's a command for this.

**Comment by sortega** [comment]
I don't know about encrypted wikis but my wiki is password protected and it works out of the box if you include the credentials in the url this way: `https://user:password@wiki.example.com`.

You only need to add this to the documentation for others to enjoy it.

**Comment by sobjornstad** [comment]
@sortega, can you comment on how you "password protect" your wiki? I have tried to get this to work with the "set password" function in TiddlyWiki activated and it does not work at all for me, so I'm wondering if you're talking about something else.

**Comment by sortega** [comment]
I have several sites in the same server and I use nginx in front of them. It's at nginx level that I have HTTP basic authentication enabled.

**Comment by sobjornstad** [comment]
Ah, that makes sense. Thanks for the clarification.

**Comment by sobjornstad** [comment]
This will be supported in the next version, along with a note in the docs on HTTP basic authentication.

**Comment by sortega** [comment]
Soren, thanks for the new goodies in release 1.3! Really appreciated.

However, my setup is no longer working with the new release. This is the relevant error snippet with my password redacted:

```
Caught exception:
Traceback (most recent call last):
  File "http/client.py", line 871, in _get_hostport
ValueError: invalid literal for int() with base 10: '*******************@tiddlywiki.refeed.org'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/importer.py", line 185, in join_thread
    if self.handle_thread_exception():
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/importer.py", line 173, in handle_thread_exception
    raise exc
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/importer.py", line 57, in run
    self.notes = twimport.find_notes(
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/twimport.py", line 248, in find_notes
    notes = _notes_from_paths(
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/twimport.py", line 110, in _notes_from_paths
    notes.update(_notes_from_tiddler(tid_text, wiki, tid_name, warnings))
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/twimport.py", line 134, in _notes_from_tiddler
    return TwNote.notes_from_soup(soup, wiki, tiddler_name, warnings)
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/twnote.py", line 147, in notes_from_soup
    notes.update(subclass.parse_html(
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/twnote.py", line 321, in parse_html
    pair = extract_media(media, pair, wiki, tiddler_name, warnings)
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/twnote.py", line 659, in extract_media
    with urlopen(open_src) as response:
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 542, in _open
  File "urllib/request.py", line 502, in _call_chain
  File "urllib/request.py", line 1393, in https_open
  File "urllib/request.py", line 1319, in do_open
  File "http/client.py", line 1382, in __init__
  File "http/client.py", line 833, in __init__
  File "http/client.py", line 876, in _get_hostport
http.client.InvalidURL: nonnumeric port: '*********@tiddlywiki.refeed.org'
```

I have non-alphanumeric characters in there just in case it's useful.

**Comment by sobjornstad** [comment]
@sortega: This is not related to #7, it's a problem with the new media syncing – can you post it in a new issue?

**Comment by sortega** [comment]
Sure
