### ISSUE TITLE
Caught exception: Traceback

### ISSUE THREAD

**Issue by alexdion64** [sobjornstad/TiddlyRemember#77]
Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0 Platform: Windows-10-10.0.22000 Flags: frz=True ao=True sv=2 Add-ons, last update check: 2023-01-26 22:11:53  

Caught exception: Traceback (most recent call last):   File "C:\Users\User\AppData\Roaming\Anki2\addons21\60456529\twimport.py", line 71, in _invoke_tw_command     proc = subprocess.run(cmd, cwd=wiki_path, stdout=subprocess.PIPE,   File "subprocess", line 528, in run subprocess.CalledProcessError: Command '['C:\\Users\\User\\AppData\\Roaming\\npm\\tiddlywiki.cmd', '--verbose', '--output', 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp7boof57n\\render', '--render', '[type[text/vnd.tiddlywiki]] [type[]] +[!is[system]]', '[encodeuricomponent[]addsuffix[.html]]', 'text/html', '$:/plugins/sobjornstad/TiddlyRemember/templates/TiddlyRememberParseable']' returned non-zero exit status 1.

**Comment by alexdion64** [comment]
Can't sync with TiddlyWiki. Help, please....
