### ISSUE TITLE
TiddlyRemember does not work on Arch Linux 

### ISSUE THREAD

**Issue by emcristi** [sobjornstad/TiddlyRemember#78]
On EndeavourOS (Arch)

```
uname --all
Linux ... 6.3.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 30 May 2023 13:44:01 +0000 x86_64 GNU/Linux

yay  -Q --info anki
Name            : anki
Version         : 2.1.65-1
Description     : Helps you remember facts (like words/phrases in a foreign language) efficiently
Architecture    : x86_64
URL             : https://apps.ankiweb.net/
Licenses        : AGPL3
Groups          : None
Provides        : None
Depends On      : python>=3.9  python-beautifulsoup4  python-waitress>=2.0.0  python-requests
                  python-decorator  python-markdown  python-orjson  python-protobuf>=4.21  python-pysocks
                  python-distro  python-flask-cors  python-jsonschema  python-send2trash  python-certifi
                  qt6-multimedia  python-pyqt6-webengine>=6.2  qt6-svg
Optional Deps   : lame: record sound [installed]
                  mpv: play sound. prefered over mplayer [installed]
                  mplayer: play sound
                  texlive-most: render LaTex in cards
Required By     : None
Optional For    : None
Conflicts With  : anki-bin  anki-git  anki-official-binary-bundle  anki-qt5
Replaces        : None
Installed Size  : 57.38 MiB
Packager        : Unknown Packager
Build Date      : Tue 06 Jun 2023 11:08:36 AM EEST
Install Date    : Tue 06 Jun 2023 11:18:02 AM EEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

When I try to run TiddlyRemember plugin (Shift-Y), I get the following error:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (141bc18b) Python 3.11.3 Qt 6.5.1 PyQt 6.5.1
Platform: Linux-6.3.5-arch1-1-x86_64-with-glibc2.37
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2023-06-06 11:25:48
Add-ons possibly involved: ⁨TiddlyRemember⁩

Caught exception:
Traceback (most recent call last):
  File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
    self.form.progressBar.setValue(at * 100 / end)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Caught exception:
Traceback (most recent call last):
  File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
    self.form.progressBar.setValue(at * 100 / end)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Caught exception:
Traceback (most recent call last):
  File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
    self.form.progressBar.setValue(at * 100 / end)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Caught exception:
Traceback (most recent call last):
  File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
    self.form.progressBar.setValue(at * 100 / end)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Caught exception:
Traceback (most recent call last):
  File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
    self.form.progressBar.setValue(at * 100 / end)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Caught exception:
Traceback (most recent call last):
  File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
    self.form.progressBar.setValue(at * 100 / end)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Caught exception:
Traceback (most recent call last):
  File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
    self.form.progressBar.setValue(at * 100 / end)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Caught exception:
Traceback (most recent call last):
  File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
    self.form.progressBar.setValue(at * 100 / end)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Caught exception:
Traceback (most recent call last):
  File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
    self.form.progressBar.setValue(at * 100 / end)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Caught exception:
Traceback (most recent call last):
  File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
    self.form.progressBar.setValue(at * 100 / end)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Caught exception:
Traceback (most recent call last):
  File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
    self.form.progressBar.setValue(at * 100 / end)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'
```

Any hints on how to debug the problem further?

**Comment by sobjornstad** [comment]
As a quick hack until I get a chance to look, I bet you can fix it manually:

Traceback (most recent call last):
  File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
    self.form.progressBar.setValue(at * 100 / end)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Change that line to:

    self.form.progressBar.setValue(at * 100 // end)

Not sure why it has suddenly started refusing to coerce floats to ints.

On Tue, Jun 6, 2023, at 03:38, Cristi wrote:
> 
> 
> On EndeavourOS (Arch)
> 
> `uname --all
> Linux ... 6.3.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 30 May 2023 13:44:01 +0000 x86_64 GNU/Linux
> 
> yay  -Q --info anki
> Name            : anki
> Version         : 2.1.65-1
> Description     : Helps you remember facts (like words/phrases in a foreign language) efficiently
> Architecture    : x86_64
> URL             : https://apps.ankiweb.net/
> Licenses        : AGPL3
> Groups          : None
> Provides        : None
> Depends On      : python>=3.9  python-beautifulsoup4  python-waitress>=2.0.0  python-requests
>                   python-decorator  python-markdown  python-orjson  python-protobuf>=4.21  python-pysocks
>                   python-distro  python-flask-cors  python-jsonschema  python-send2trash  python-certifi
>                   qt6-multimedia  python-pyqt6-webengine>=6.2  qt6-svg
> Optional Deps   : lame: record sound [installed]
>                   mpv: play sound. prefered over mplayer [installed]
>                   mplayer: play sound
>                   texlive-most: render LaTex in cards
> Required By     : None
> Optional For    : None
> Conflicts With  : anki-bin  anki-git  anki-official-binary-bundle  anki-qt5
> Replaces        : None
> Installed Size  : 57.38 MiB
> Packager        : Unknown Packager
> Build Date      : Tue 06 Jun 2023 11:08:36 AM EEST
> Install Date    : Tue 06 Jun 2023 11:18:02 AM EEST
> Install Reason  : Explicitly installed
> Install Script  : No
> Validated By    : None
`
> When I try to run TiddlyRemember plugin (Shift-Y), I get the following error:
> 
> `Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
> Debug info:
> Anki 2.1.65 (141bc18b) Python 3.11.3 Qt 6.5.1 PyQt 6.5.1
> Platform: Linux-6.3.5-arch1-1-x86_64-with-glibc2.37
> Flags: frz=False ao=True sv=2
> Add-ons, last update check: 2023-06-06 11:25:48
> Add-ons possibly involved: ⁨TiddlyRemember⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
>     self.form.progressBar.setValue(at * 100 / end)
> TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'
> 
> Caught exception:
> Traceback (most recent call last):
>   File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
>     self.form.progressBar.setValue(at * 100 / end)
> TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'
> 
> Caught exception:
> Traceback (most recent call last):
>   File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
>     self.form.progressBar.setValue(at * 100 / end)
> TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'
> 
> Caught exception:
> Traceback (most recent call last):
>   File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
>     self.form.progressBar.setValue(at * 100 / end)
> TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'
> 
> Caught exception:
> Traceback (most recent call last):
>   File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
>     self.form.progressBar.setValue(at * 100 / end)
> TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'
> 
> Caught exception:
> Traceback (most recent call last):
>   File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
>     self.form.progressBar.setValue(at * 100 / end)
> TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'
> 
> Caught exception:
> Traceback (most recent call last):
>   File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
>     self.form.progressBar.setValue(at * 100 / end)
> TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'
> 
> Caught exception:
> Traceback (most recent call last):
>   File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
>     self.form.progressBar.setValue(at * 100 / end)
> TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'
> 
> Caught exception:
> Traceback (most recent call last):
>   File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
>     self.form.progressBar.setValue(at * 100 / end)
> TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'
> 
> Caught exception:
> Traceback (most recent call last):
>   File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
>     self.form.progressBar.setValue(at * 100 / end)
> TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'
> 
> Caught exception:
> Traceback (most recent call last):
>   File "/home/cristi/.local/share/Anki2/addons21/60456529/importer.py", line 124, in extract_progress
>     self.form.progressBar.setValue(at * 100 / end)
> TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'
`

**Comment by emcristi** [comment]
Yes, using the integer division operator `//` fixed the problem. 
Thank you for the quick reply.
