### ISSUE TITLE
TiddlyRemember won't sync - "Error while parsing tiddler."

### ISSUE THREAD

**Issue by surilean** [sobjornstad/TiddlyRemember#84]
Hey! I just installed TiddlyRemember for Anki and TiddlyWiki. When I try to sync, it starts "exporting" but it stops at the alphabetically very first tiddler of my wiki. Then it spits out the following message. It seems like all I'd have to do is import the 1.3.4 TiddlyRemember plugin version to TiddlyWiki, but I don't know how to do that, since the drag and drop method only worked for 1.3.5. I hope someone has the patience and know-how to help me... thanks.

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\60456529\twimport.py", line 113, in _notes_from_paths
    notes.update(_notes_from_tiddler(tid_text, wiki, tid_name, warnings))
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\60456529\twimport.py", line 141, in _notes_from_tiddler
    ensure_version(soup)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\60456529\twnote.py", line 622, in ensure_version
    raise ConfigurationError(
60456529.oops.ConfigurationError: Your Anki plugin is at version 1.3.5, but your TiddlyWiki plugin is at version 1.3.5. This version of the Anki plugin is compatible with the following TiddlyRemember plugin versions: 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4. Please update your Anki and TiddlyWiki plugins to the latest version, then try syncing again.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\60456529\importer.py", line 63, in run
    self.notes = twimport.find_notes(
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\60456529\twimport.py", line 257, in find_notes
    notes = _notes_from_paths(
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\60456529\twimport.py", line 118, in _notes_from_paths
    raise TiddlerParsingError(tiddler_name) from e
60456529.oops.TiddlerParsingError: Could not parse tiddler AlexanderOfPherae.
```

**Comment by surilean** [comment]
Oops... see #82 by emcristi. What you have to do is navigate to your "util.py" and manually add "1.3.5" to the list of versions. I should've checked before I posted this but now I can't seem to delete it...
